appveyor:
  secure: {BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WnfZNnJ9dcVFEihjx464vljvjN0e+5/SvE7oxIp2DoC/oL62KhlxPqL8ZMPZ6+l9z2/xmPD60sZamfsxvdN1xMe3SUwvJPguaobGMcROdAh/UBwyAb/LZtKJxV3M3OjEpqkHGM7wpOWxpIyHNv2MhFMc3XJuUSdxDM5hrrkHhDbC79SBU7dwtLXgUh/W8uUkT1+TNbLvDC6In8U1wQmuGXukbaHTeTy/A9F8DwQ87+eay6adQiFkIJBWpJ5h4S3uMZnnE8D55PD/qx99kJ3IrX9tBQ6b1GDHdXpmbund8b4mkGS3kU3WfHxAkoJvTmdKe1x0EplBvWx6ceDSzY2IEUEAJnMfbThKteAb0fetCqSU8Vup+jlTYJMmusQcAyI7PEngpbB9LWjbMXe8gcB1jsA7Lva/XWI73G+hArCPRZxoaLNc2la7TZyd7+zpQVpA8CCqOEYYEbdTmpKu8NBlhHN+3qTkNkXJqW+0DXBqD3i8UVEtvtv/m+GNgQt4NNQYIsppK+Np3aPDVVSIdpl0cl2VOBOf9+VMNtU1/pVFnKDUAgPuUu09H+TE9kdj8tritiSQe38twnOfm0bhh/Z/w6vmtP+Rs9VNsEKKzVBtkHHyj0pJTn4HBX9Fu/LsARRBaNUwxbskCQWzf9fY8RLyoj/N8k6vKIqmzM6dRcL40Mg=}
